// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Wayfarer",
    platforms: [
        .iOS("18.0")
    ],
    products: [
        .iOSApplication(
            name: "Wayfarer",
            targets: ["AppModule"],
            bundleIdentifier: "frncg.Wayfarer",
            teamIdentifier: "2FDRM8TA79",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ],
            appCategory: .puzzleGames
        )
    ],
    dependencies: [
        .package(url: "https://github.com/simibac/ConfettiSwiftUI.git", "2.0.2"..<"3.0.0"),
        .package(url: "https://github.com/bpisano/Sticker.git", "1.4.0"..<"2.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "ConfettiSwiftUI", package: "confettiswiftui"),
                .product(name: "Sticker", package: "sticker")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)